name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - frontend/**

defaults:
  run:
    working-directory: frontend

jobs:
  main:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: frontend/Dockerfile
          pull: true
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest